"""initial_schema

Revision ID: ee8b325e65dd
Revises:
Create Date: 2026-01-30 02:06:07.216659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ee8b325e65dd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("inviteCode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inviteCode"),
    )
    op.create_table(
        "Program",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isPublic", sa.Boolean(), nullable=False),
        sa.Column("creatorId", sa.Integer(), nullable=False),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asceticism_packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("creatorId", sa.Integer(), nullable=False),
        sa.Column("isPublished", sa.Boolean(), nullable=False),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mass_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("emailVerified", sa.DateTime(), nullable=True),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("USER", "MODERATOR", "ADMIN", name="userrole"),
            server_default=sa.text("'USER'"),
            nullable=False,
        ),
        sa.Column(
            "isBanned", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "verification_token",
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("identifier", "token"),
    )
    op.create_table(
        "Asceticism",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isTemplate", sa.Boolean(), nullable=False),
        sa.Column("creatorId", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("BOOLEAN", "NUMERIC", "TEXT", name="trackingtype"),
            nullable=False,
        ),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creatorId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "GroupMember",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("groupId", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("MEMBER", "ADMIN", "MENTOR", name="grouprole"),
            nullable=False,
        ),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["groupId"],
            ["Group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "UserProgram",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("programId", sa.Integer(), nullable=False),
        sa.Column("startDate", sa.DateTime(), nullable=False),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["programId"],
            ["Program.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "providerAccountId",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expires_at", sa.BigInteger(), nullable=True),
        sa.Column("id_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("session_state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["userId"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_reading_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column(
            "sessionToken", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.ForeignKeyConstraint(["userId"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sessionToken"),
    )
    op.create_table(
        "ProgramItem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("programId", sa.Integer(), nullable=False),
        sa.Column("asceticismId", sa.Integer(), nullable=False),
        sa.Column("dayStart", sa.Integer(), nullable=False),
        sa.Column("dayEnd", sa.Integer(), nullable=True),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asceticismId"],
            ["Asceticism.id"],
        ),
        sa.ForeignKeyConstraint(
            ["programId"],
            ["Program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "UserAsceticism",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("asceticismId", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "PAUSED", "COMPLETED", "ARCHIVED", name="asceticismstatus"
            ),
            nullable=False,
        ),
        sa.Column("startDate", sa.DateTime(), nullable=False),
        sa.Column("endDate", sa.DateTime(), nullable=True),
        sa.Column("targetValue", sa.Float(), nullable=True),
        sa.Column("reminderTime", sa.DateTime(), nullable=True),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asceticismId"], ["Asceticism.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["userId"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "package_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("packageId", sa.Integer(), nullable=False),
        sa.Column("asceticismId", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asceticismId"], ["Asceticism.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["packageId"], ["asceticism_packages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "AsceticismLog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userAsceticismId", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("custom_metadata", sa.JSON(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userAsceticismId"], ["UserAsceticism.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("AsceticismLog")
    op.drop_table("package_items")
    op.drop_table("UserAsceticism")
    op.drop_table("ProgramItem")
    op.drop_table("sessions")
    op.drop_table("daily_reading_notes")
    op.drop_table("accounts")
    op.drop_table("UserProgram")
    op.drop_table("GroupMember")
    op.drop_table("Asceticism")
    op.drop_table("verification_token")
    op.drop_table("users")
    op.drop_table("mass_readings")
    op.drop_table("asceticism_packages")
    op.drop_table("Program")
    op.drop_table("Group")
    # ### end Alembic commands ###
