/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/asceticisms/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Asceticisms
         * @description List all available asceticism templates.
         */
        get: operations["list_asceticisms_asceticisms__get"];
        put?: never;
        /**
         * Create Asceticism
         * @description Create a new asceticism.
         */
        post: operations["create_asceticism_asceticisms__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asceticisms/{asceticism_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Asceticism
         * @description Update an existing asceticism template.
         */
        put: operations["update_asceticism_asceticisms__asceticism_id__put"];
        post?: never;
        /**
         * Delete Asceticism
         * @description Delete an asceticism template.
         */
        delete: operations["delete_asceticism_asceticisms__asceticism_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asceticisms/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Asceticisms
         * @description Get all asceticisms for a specific user that overlap with the date range.
         */
        get: operations["list_user_asceticisms_asceticisms_my_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asceticisms/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Asceticism
         * @description Subscribe a user to an asceticism.
         */
        post: operations["join_asceticism_asceticisms_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asceticisms/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Daily Progress
         * @description Log progress for a specific day.
         */
        post: operations["log_daily_progress_asceticisms_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asceticisms/leave/{user_asceticism_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave Asceticism
         * @description Leave/remove an asceticism commitment.
         */
        delete: operations["leave_asceticism_asceticisms_leave__user_asceticism_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asceticisms/my/{user_asceticism_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Asceticism
         * @description Update a user's asceticism commitment.
         */
        patch: operations["update_user_asceticism_asceticisms_my__user_asceticism_id__patch"];
        trace?: never;
    };
    "/asceticisms/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Progress
         * @description Get progress statistics for all user asceticisms within a date range.
         */
        get: operations["get_user_progress_asceticisms_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Debug User
         * @description Create a debug user for testing purposes.
         */
        post: operations["create_debug_user_debug_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Users
         * @description Get all users with their details and activity counts.
         *     Requires admin authentication.
         */
        get: operations["get_all_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update User Role
         * @description Update a user's role.
         *     Prevents admins from demoting themselves.
         */
        post: operations["update_user_role_admin_users_role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle User Ban
         * @description Ban or unban a user.
         *     Prevents admins from banning themselves.
         */
        post: operations["toggle_user_ban_admin_users_ban_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/current-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current user info including role and ban status.
         */
        get: operations["get_current_user_admin_current_user_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Package
         * @description Create a new asceticism package (admin only).
         */
        post: operations["create_package_packages__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/admin/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Packages Admin
         * @description Get all packages including unpublished ones (admin only).
         */
        get: operations["get_all_packages_admin_packages_admin_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Package Details
         * @description Get details of a specific published package.
         */
        get: operations["get_package_details_packages__package_id__get"];
        /**
         * Update Package
         * @description Update a package (admin only).
         */
        put: operations["update_package_packages__package_id__put"];
        post?: never;
        /**
         * Delete Package
         * @description Delete a package (admin only).
         */
        delete: operations["delete_package_packages__package_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Package
         * @description Publish or unpublish a package (admin only).
         */
        post: operations["publish_package_packages__package_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse Published Packages
         * @description Get all published packages (available to all users).
         */
        get: operations["browse_published_packages_packages_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/add-to-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Package To Account
         * @description Add all asceticisms from a package to the user's account.
         */
        post: operations["add_package_to_account_packages__package_id__add_to_account_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-readings/readings/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mass Readings
         * @description Get Mass readings for a specific date. Checks database cache first,
         *     then fetches from Universalis API if not cached.
         *     Date should be in YYYYMMDD format (e.g., 20260105).
         */
        get: operations["get_mass_readings_daily_readings_readings__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-readings/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Or Update Note
         * @description Create or update a daily reading note for a user on a specific date.
         */
        post: operations["create_or_update_note_daily_readings_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-readings/notes/{user_id}/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Note By Date
         * @description Get a user's daily reading note for a specific date.
         *     Returns 404 if no note exists for that date.
         */
        get: operations["get_note_by_date_daily_readings_notes__user_id___date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-readings/notes/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All User Notes
         * @description Get all daily reading notes for a user, ordered by date descending.
         */
        get: operations["get_all_user_notes_daily_readings_notes__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-readings/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Note
         * @description Delete a daily reading note by ID.
         */
        delete: operations["delete_note_daily_readings_notes__note_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Health check endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AsceticismCreate
         * @description Request to create an asceticism.
         */
        AsceticismCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Category */
            category: string;
            /** Icon */
            icon?: string | null;
            /** @default BOOLEAN */
            type: components["schemas"]["TrackingType"];
            /** Custom Metadata */
            custom_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Creatorid */
            creatorId?: number | null;
        };
        /**
         * AsceticismInfo
         * @description Asceticism information for package items.
         */
        AsceticismInfo: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Category */
            category: string;
            /** Icon */
            icon: string | null;
            /** Type */
            type: string;
        };
        /**
         * AsceticismResponse
         * @description Asceticism response.
         */
        AsceticismResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Category */
            category: string;
            /** Icon */
            icon: string | null;
            type: components["schemas"]["TrackingType"];
            /** Istemplate */
            isTemplate: boolean;
            /** Creatorid */
            creatorId: number | null;
            /** Custom Metadata */
            custom_metadata: {
                [key: string]: unknown;
            } | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * AsceticismStatus
         * @description Status of a user's asceticism commitment.
         * @enum {string}
         */
        AsceticismStatus: "ACTIVE" | "PAUSED" | "COMPLETED" | "ARCHIVED";
        /**
         * CurrentUserResponse
         * @description Current user information.
         */
        CurrentUserResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Role */
            role: string;
            /** Isbanned */
            isBanned: boolean;
        };
        /**
         * DailyReadingNoteCreate
         * @description Request to create or update a daily reading note.
         */
        DailyReadingNoteCreate: {
            /** Userid */
            userId: number;
            /** Date */
            date: string;
            /** Notes */
            notes: string;
        };
        /**
         * DailyReadingNoteResponse
         * @description Daily reading note response.
         */
        DailyReadingNoteResponse: {
            /** Id */
            id: number;
            /** Userid */
            userId: number;
            /** Date */
            date: string;
            /** Notes */
            notes: string;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LogCreate
         * @description Request to create asceticism log.
         */
        LogCreate: {
            /** Userasceticismid */
            userAsceticismId: number;
            /** Date */
            date: string;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Value */
            value?: number | null;
            /** Notes */
            notes?: string | null;
            /** Custom Metadata */
            custom_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * LogResponse
         * @description Asceticism log response.
         */
        LogResponse: {
            /** Id */
            id: number;
            /** Userasceticismid */
            userAsceticismId: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Completed */
            completed: boolean;
            /** Value */
            value: number | null;
            /** Notes */
            notes: string | null;
            /** Custom Metadata */
            custom_metadata: {
                [key: string]: unknown;
            } | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * PackageCreate
         * @description Request to create a package.
         */
        PackageCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Custom Metadata */
            custom_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Items */
            items: components["schemas"]["PackageItemInput"][];
        };
        /**
         * PackageItemInput
         * @description Package item input.
         */
        PackageItemInput: {
            /** Asceticismid */
            asceticismId: number;
            /**
             * Order
             * @default 0
             */
            order: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * PackageItemResponse
         * @description Package item response.
         */
        PackageItemResponse: {
            /** Id */
            id: number;
            /** Asceticismid */
            asceticismId: number;
            /** Order */
            order: number;
            /** Notes */
            notes: string | null;
            asceticism: components["schemas"]["AsceticismInfo"];
        };
        /**
         * PackageResponse
         * @description Package response.
         */
        PackageResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Creatorid */
            creatorId: number;
            /** Ispublished */
            isPublished: boolean;
            /** Custom Metadata */
            custom_metadata: {
                [key: string]: unknown;
            } | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Items */
            items: components["schemas"]["PackageItemResponse"][];
            /** Itemcount */
            itemCount: number;
        };
        /**
         * PackageUpdate
         * @description Request to update a package.
         */
        PackageUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Custom Metadata */
            custom_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Items */
            items?: components["schemas"]["PackageItemInput"][] | null;
        };
        /**
         * ToggleBanRequest
         * @description Request to ban or unban a user.
         */
        ToggleBanRequest: {
            /** Userid */
            userId: number;
            /** Isbanned */
            isBanned: boolean;
        };
        /**
         * TrackingType
         * @description Tracking type enumeration for asceticisms.
         * @enum {string}
         */
        TrackingType: "BOOLEAN" | "NUMERIC" | "TEXT";
        /**
         * UpdateRoleRequest
         * @description Request to update user role.
         */
        UpdateRoleRequest: {
            /** Userid */
            userId: number;
            /** Newrole */
            newRole: string;
        };
        /**
         * UserAsceticismLink
         * @description Request to link user to asceticism.
         */
        UserAsceticismLink: {
            /** Userid */
            userId: number;
            /** Asceticismid */
            asceticismId: number;
            /** Targetvalue */
            targetValue?: number | null;
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Custom Metadata */
            custom_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * UserAsceticismUpdate
         * @description Request to update user asceticism.
         */
        UserAsceticismUpdate: {
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Targetvalue */
            targetValue?: number | null;
            status?: components["schemas"]["AsceticismStatus"] | null;
        };
        /**
         * UserResponse
         * @description User response with activity counts.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Image */
            image: string | null;
            /** Role */
            role: string;
            /** Isbanned */
            isBanned: boolean;
            /** Emailverified */
            emailVerified: string | null;
            /** Userasceticismscount */
            userAsceticismsCount: number;
            /** Groupmemberscount */
            groupMembersCount: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_asceticisms_asceticisms__get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsceticismResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_asceticism_asceticisms__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsceticismCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsceticismResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asceticism_asceticisms__asceticism_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asceticism_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsceticismCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsceticismResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asceticism_asceticisms__asceticism_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asceticism_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_asceticisms_asceticisms_my_get: {
        parameters: {
            query: {
                userId: number;
                startDate?: string | null;
                endDate?: string | null;
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_asceticism_asceticisms_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAsceticismLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_daily_progress_asceticisms_log_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_asceticism_asceticisms_leave__user_asceticism_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_asceticism_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_asceticism_asceticisms_my__user_asceticism_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_asceticism_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAsceticismUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_progress_asceticisms_progress_get: {
        parameters: {
            query: {
                userId: number;
                startDate: string;
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_debug_user_debug_user_post: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_users_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_role_admin_users_role_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_user_ban_admin_users_ban_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleBanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_admin_current_user_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_package_packages__post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_packages_admin_packages_admin_all_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_details_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_package_packages__package_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_package_packages__package_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_package_packages__package_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_published_packages_packages_browse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageResponse"][];
                };
            };
        };
    };
    add_package_to_account_packages__package_id__add_to_account_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-email"?: string | null;
            };
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mass_readings_daily_readings_readings__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_or_update_note_daily_readings_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyReadingNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReadingNoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_by_date_daily_readings_notes__user_id___date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReadingNoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_user_notes_daily_readings_notes__user_id__get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReadingNoteResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_daily_readings_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
